version: '3.1'

services:
  db:
    volumes:
      - broker_db:/var/lib/postgresql/data

  mq:
    ports:
      # It is easier to use nginx without port number clashes so
      # nginx will accept a connection on 1883, forward it to
      # 127.0.0.1:1884, which docker will forward to port 1883
      # within the container.
      - "127.0.0.1:1884:1883"
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:15692:15692"
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia/rabbit@mq

  restapi:
    ports:
      - "127.0.0.1:5687:5687"

  ttn_webhook:
    ports:
      - "127.0.0.1:5688:5688"
  
  website:
    ports:
      - "127.0.0.1:5000:5000"

volumes:
  broker_db:
    external: true

  mq_data:
    external: true
