---
modules:
  default:
    metrics:
    - name: l_uid 
      path: "{ .values.l_uid }"
      epochTimestamp: "{ .values.timestamp }"
      help: logical id
      labels:
        p_uid: "{ .values.p_uid }"
        deviceName: "{ .values.timeseries.name }"
      values:
        deviceValue: "{ .values.timeseries.value }"    