---
modules:
  default:
    metrics:
    - name: l_uid 
      path: "{ .l_uid }"
      epochTimestamp: "{ .timestamp }"
      help: logical id
      labels:
        p_uid: "{ .p_uid }"
        deviceName: "{ .name }"
      values:
        deviceValue: "{ .value }"    