#!/bin/bash

for ((i = 1; i <= 10; i++)); do
	timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
	battery_voltage=$((RANDOM % 10))

	payload='{
        "broker_correlation_id": "83d04e6f-db16-4280-8337-53f11b2335c6",
        "p_uid": 999,
        "l_uid": 666,
        "timestamp": "'"$timestamp"'",
        "timeseries": [
            {
                "name": "battery (v)",
                "value": '"$battery_voltage"'
            }
        ]
    }'

	docker exec test-mq-1 rabbitmqadmin publish -u broker -p CHANGEME exchange="lts_exchange" routing_key="ltsreader_logical_msg_queue" payload="$payload" properties="{}"

	echo "$payload"
	sleep 1
done
