CREATE EXTENSION postgis;
CREATE EXTENSION pgcrypto;

create table if not exists sources (
    source_name text primary key not null
);

create table if not exists physical_devices (
    uid integer generated always as identity primary key,
    source_name text not null references sources,
    name text not null,
    location geometry('POINT', 4283),
    last_seen timestamptz,
    -- Store only top level key value pairs here; it is used
    -- for quickly finding a device using information carried
    -- in a message such as a deveui or sensor group id.
    source_ids jsonb,
    -- Store more complete information about the source device
    -- in this column. Information such as description or
    -- attributes that may be useful to downstream processes
    -- can go here.
    -- The correlation ID of the message that caused a device
    -- to be created should also be stored in here under the
    -- key creation-correlation-id.
    properties jsonb not null default '{}'
);

create table if not exists physical_timeseries ( 
    uid integer generated always as identity primary key,
    physical_uid integer not null references physical_devices(uid),
    -- The logical_uid will be null for messages from unmapped devices. This is ok.
    logical_uid integer,
    -- Mapper processing state: 0 pending, 1 claimed, 2 success, 3 failed_permanent, 4 skipped.
    map_state smallint not null default 0,
    received_at timestamptz not null default now(),
    ts timestamptz not null,
    ts_delta interval,
    -- The message is stored in the brokers format as a JSONB object.
    json_msg jsonb not null,
    constraint pts_map_state_valid_ck check (map_state in (0, 1, 2, 3, 4))
);

create table if not exists logical_timeseries (
    uid integer generated always as identity primary key,
    physical_uid integer not null references physical_devices(uid),
    logical_uid integer,
    received_at timestamptz not null default now(),
    ts timestamptz not null,
    ts_delta interval,
    json_msg jsonb not null
);

create table if not exists raw_messages (
    uid integer generated always as identity primary key,
    source_name text not null references sources,
    -- Some front-end-processors will have the physical uid
    -- available when they write these messages so include this
    -- as an optional column. The split processing in TTN could
    -- have this updated by the second process, using the correlation id
    -- to find the raw_messages row after it has the physical device.
    physical_uid integer,
    -- The correlation ID must be generated by the front end
    -- processors that receive the messages.
    correlation_id uuid unique not null,
    ts timestamptz not null,
    -- If the source system uses JSON for its message format
    -- then the messages get stored in this column.
    json_msg jsonb,
    -- If the source system uses CSV or similar then the messages
    -- get stored in this column.
    text_msg text
);

create table if not exists device_notes (
    uid integer generated always as identity primary key,
    physical_uid integer references physical_devices(uid),
    ts timestamptz not null default now(),
    note text not null
);

create table if not exists device_blobs (
    uid integer generated always as identity primary key,
    physical_uid integer references physical_devices(uid),
    ts timestamptz not null default now(),
    data bytea not null
);

create table if not exists logical_devices (
    uid integer generated always as identity primary key,
    name text not null,
    location geometry('POINT', 4283),
    last_seen timestamptz,
    properties jsonb not null default '{}'
);

create table if not exists physical_logical_map (
    uid integer generated always as identity primary key,
    -- Keep mapping identity anchored by physical/logical device ids and an
    -- active datetime range.
    physical_uid integer not null references physical_devices(uid),
    logical_uid integer not null references logical_devices(uid),
    active_range tstzrange not null default tstzrange(now(), null, '[)'),
    is_active boolean NOT NULL DEFAULT true,
    constraint plm_active_range_bounds_ck check (
        lower_inc(active_range)
        and not upper_inc(active_range)
        and not isempty(active_range)
    )
);

create table if not exists users (
    uid integer generated always as identity primary key,
    username text not null unique,
    salt text not null,
    password text not null,
    auth_token text not null,
    valid boolean not null,
    read_only boolean default True not null
);

create table if not exists version (
    version integer not null
);

create or replace function update_timeseries_ts_delta()
returns trigger as $$
begin
    NEW.ts_delta = NEW.received_at - NEW.ts;
    return NEW;
end;
$$ language plpgsql;

drop trigger if exists update_physical_timeseries_ts_delta_trigger on physical_timeseries;

create trigger update_physical_timeseries_ts_delta_trigger
before insert or update on physical_timeseries
for each row
execute function update_timeseries_ts_delta();

drop trigger if exists update_logical_timeseries_ts_delta_trigger on logical_timeseries;

create trigger update_logical_timeseries_ts_delta_trigger
before insert or update on logical_timeseries
for each row
execute function update_timeseries_ts_delta();

create index if not exists pd_src_id_idx on physical_devices using GIN (source_ids);

create unique index if not exists plm_logical_lower_uidx
    on physical_logical_map (logical_uid, lower(active_range));

create unique index if not exists plm_physical_logical_lower_uidx
    on physical_logical_map (physical_uid, logical_uid, lower(active_range));

-- Optimise current mapping lookups in DAO.get_current_device_mapping() and
-- update/end-mapping operations that filter on an open upper bound.
create index if not exists plm_current_physical_lower_idx
    on physical_logical_map (physical_uid, lower(active_range) desc)
    where upper(active_range) is null;

create index if not exists plm_current_logical_lower_idx
    on physical_logical_map (logical_uid, lower(active_range) desc)
    where upper(active_range) is null;

-- Optimise historical timeseries reads used by the REST API when filtering
-- by device uid and timestamp range with order by ts desc.
create index if not exists pts_physical_uid_ts_desc_idx
    on physical_timeseries (physical_uid, ts desc);

create index if not exists pts_logical_uid_ts_desc_idx
    on physical_timeseries (logical_uid, ts desc)
    where logical_uid is not null;

create index if not exists pts_pending_uid_idx
    on physical_timeseries (uid)
    where map_state = 0;

create index if not exists lts_physical_uid_ts_desc_idx
    on logical_timeseries (physical_uid, ts desc);

create index if not exists lts_logical_uid_ts_desc_idx
    on logical_timeseries (logical_uid, ts desc)
    where logical_uid is not null;

insert into sources values ('ttn'), ('greenbrain'), ('wombat'), ('ydoc'), ('ict_eagleio');
insert into version values (3);
