sequenceDiagram
    autonumber
    participant MQp as MQ[physical_timeseries]
    participant DM as Device Mapper
    participant DB
    participant MQl as MQ[logical_timeseries]
    participant uw as Ubidots Writer
    activate MQp
    MQp-)DM: {physical device id, timestamp, data points}
    activate DM
    deactivate MQp
    activate DB
    DM->>DB: get mapping for physical device id
    DB-->>DM: {physical device, logical device}
    deactivate DB
    activate MQl
    DM-)MQl: {physical device id, logical device id, timestamp, data points}
    activate MQp
    DM-)MQp: {ack}
    deactivate DM
    MQp->>MQp: delete persisted message
    deactivate MQp
    MQl->>MQl: persist message
    MQl-)DM: {ack} IGNORED
    deactivate MQl
    activate MQl
    activate uw
    MQl-)uw: {physical device id, logical device id, timestamp, data points}
    activate DB
    uw->>DB: get logical device
    DB-->>uw: logical device
    deactivate DB
    uw->>Ubidots: POST timeseries to device
    uw-)MQl: {ack}
    deactivate uw
    MQl->>MQl: delete persisted message
    deactivate MQl
