version: '3.1'

services:
  db:
    image: postgres:14.2
    restart: "no"
    env_file:
      - .env
    volumes:
      - ../db/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PGDATABASE}", "-U", "${PGUSER}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  mq:
    hostname: "mq"
    image: rabbitmq:3.9-management
    restart: "no"
    env_file:
      - .env
    volumes:
      - ../config/rabbitmq:/etc/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity || exit 1
      interval: 30s
      start_period: 30s

  restapi:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      - "db"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/restapi"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5687", "RestAPI:app" ]
    healthcheck:
      test: curl --fail -I http://localhost:5687/openapi.json || exit 1
      interval: 1m
      start_period: 20s

  website:
    image: broker/mgmt-app
    env_file:
      - .env
    depends_on:
      restapi:
        condition: "service_healthy"
    volumes:
      - ../src/www:/app

  ttn_webhook:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    profiles:
      - ttn
    depends_on:
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5688", "WebHook:app" ]

  ttn_processor:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    profiles:
      - ttn
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
      ttn_decoder:
        condition: "service_started"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "python", "AllMsgsWriter.py" ]

  ttn_decoder:
    image: broker/ttn_decoder
    restart: "no"
    env_file:
      - .env
    profiles:
      - ttn
    volumes:
      - ../src/js/ttn_decoder/src:/usr/src/ttn_decoder/src
      - ../../ttn-formatters/:/usr/src/ttn_formatters
    working_dir: "/usr/src/ttn_decoder"
    entrypoint: [ "node", "src" ]

  mqtt_processors:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    profiles:
      - mqttprocessors
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "mqtt_processors.MQTTProcessors" ]

  lm:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "logical_mapper.LogicalMapper" ]

  delivery:
    image: broker/python-base:latest
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - ubidots
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "delivery.UbidotsWriter" ]

  pollers:
    image: broker/python-base
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - pollers
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "pollers.ICT_EagleIO" ]

  frred:
    image: broker/python-base
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - frred
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
      - ${DATABOLT_SHARED_DIR}/raw_data:/raw_data
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "delivery.FRRED" ]

  prometheus:
    image: prom/prometheus
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
