version: '3.1'

services:
  db:
    image: postgis/postgis:14-3.4
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../db/init.d:/docker-entrypoint-initdb.d
      - ../db/upgrade:/upgrade
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PGDATABASE}", "-U", "${PGUSER}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  mq:
    hostname: "mq"
    image: rabbitmq:3.9-management
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../config/rabbitmq:/etc/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity || exit 1
      interval: 30s
      start_period: 30s

  restapi:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - "db"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/restapi"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5687", "RestAPI:app" ]

  website:
    image: broker/mgmt-app
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/iota
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - ../src/www:/app
      - ../src/python:/iota

  ttn_webhook:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - ttn
    depends_on:
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5688", "WebHook:app" ]

  ttn_processor:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - ttn
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
      ttn_decoder:
        condition: "service_started"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "python", "AllMsgsWriter.py" ]

  ttn_decoder:
    image: broker/ttn_decoder
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - ttn
    volumes:
      - ../src/js/ttn_decoder/src:/usr/src/ttn_decoder/src
      - ../../ttn-formatters/:/usr/src/ttn_formatters
    working_dir: "/usr/src/ttn_decoder"
    entrypoint: [ "node", "src" ]

  ydoc:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - ydoc
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "ydoc.YDOC" ]

  wombat:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles: ["wombat", "frred"]
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "ydoc.Wombat" ]

  lm:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "logical_mapper.LogicalMapper" ]

  delivery:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - ubidots
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "delivery.UbidotsWriter" ]

  pollers:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - pollers
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "pollers.ICT_EagleIO" ]

  frred:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - frred
    depends_on:
      db:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
      - ${DATABOLT_SHARED_DIR}/nectar_raw_data:/raw_data
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "delivery.FRRED" ]


  axistech:
    image: broker/python-base
    logging:
      driver: local
      options:
        max-file: "3"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - frred
    depends_on:
      db:
    entrypoint: [ "python", "-m", "pollers.axistech" ]
    
  timescaledb:
    build: ../timescale  # Point to the directory containing the custom Dockerfile
    hostname: "tsdb"
    image: custom-timescaledb:latest
    restart: "no"    

    env_file:
      - .tsdb_env
    volumes:
      - ../timescale/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../timescale/pgbackrest/pgbackrest.conf:/home/postgres/pgdata/backup/pgbackrest.conf
      - ../timescale/logs:/var/log/timescale
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TSDB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  iota_tsdb_decoder:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      timescaledb:
        condition: "service_healthy"
      mq:
        condition: "service_healthy"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "timescale.TS_LTSReader" ]
