# Generated by Django 6.0.4 on 2026-04-10 02:43

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBlob',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('data', models.BinaryField()),
            ],
            options={
                'db_table': 'device_blobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceNote',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'device_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogicalDevice',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4283)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('properties', models.JSONField()),
            ],
            options={
                'db_table': 'logical_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogicalTimeseries',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('logical_uid', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('ts', models.DateTimeField()),
                ('ts_delta', models.DurationField(blank=True, null=True)),
                ('json_msg', models.JSONField()),
            ],
            options={
                'db_table': 'logical_timeseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalDevice',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4283)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('source_ids', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField()),
            ],
            options={
                'db_table': 'physical_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalLogicalMap',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('active_range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'physical_logical_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalTimeseries',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('logical_uid', models.IntegerField(blank=True, null=True)),
                ('map_state', models.SmallIntegerField(default=0)),
                ('received_at', models.DateTimeField()),
                ('ts', models.DateTimeField()),
                ('ts_delta', models.DurationField(blank=True, null=True)),
                ('json_msg', models.JSONField()),
            ],
            options={
                'db_table': 'physical_timeseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('physical_uid', models.IntegerField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(unique=True)),
                ('ts', models.DateTimeField()),
                ('json_msg', models.JSONField(blank=True, null=True)),
                ('text_msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('salt', models.TextField()),
                ('password', models.TextField()),
                ('auth_token', models.TextField()),
                ('valid', models.BooleanField()),
                ('read_only', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
