apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: broker
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          hostPath:
            path: /opt/broker_data/grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: broker
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
