apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: broker
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          command:
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
      volumes:
        - name: prometheus-config
          hostPath:
            path: /opt/broker/config/prometheus.yml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: broker
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
